@echo off
@echo Installing drivers
@echo ...
@echo ....
@echo ........
@echo installing vcredist
start /wait vcredist/vcredist2008_x86.exe /qb
@echo ...
@echo ....
@echo ........
@echo installing DirectX
start /wait vcredist/DXSETUP.exe /silent
@echo ...
@echo ....
@echo ........
@echo Opening Launcher
start /wait Lanucher.exe
exit;